const demoQuiz = [
  {
    title: "All are living thing except",
    a: "Human",
    b: "Animal",
    c: "Plant",
    d: "Chair",
    correct: "d",
  },
  {
    title: "How many teeth does",
    a: "30",
    b: "31",
    c: "32",
    d: "33",
    correct: "c",
  },
  {
    title: "How many planets our solar system have?",
    a: "10",
    b: "9",
    c: "8",
    d: "7",
    correct: "b",
  },
  {
    title: "What is the name of our galaxy",
    a: "Milky Way",
    b: "Highway",
    c: "Motorway",
    d: "Starwars",
    correct: "a",
  },
  {
    title: "Which birds have sharp eyes?",
    a: "Sparrow",
    b: "Pigeon",
    c: "Eagle",
    d: "Crow",
    correct: "c",
  },
  {
    title: "How many hours are there in a day?",
    a: "24",
    b: "22",
    c: "23",
    d: "26",
    correct: "a",
  },
  {
    title: "What is the formula of Oxygen",
    a: "O",
    b: "O2",
    c: "CO2",
    d: "NO2",
    correct: "b",
  },
  {
    title: "How many bones does a human have?",
    a: "200",
    b: "201",
    c: "206",
    d: "208",
    correct: "c",
  },
  {
    title: "Who was the first person to land on the moon",
    a: "Elon Musk",
    b: "Mukesh Ambani",
    c: "Bilagtes",
    d: "Nelam Stone",
    correct: "d",
  },
  {
    title: "which is the largest content of the world",
    a: "Asia",
    b: "Europe",
    c: "Australlia",
    d: "America",
    correct: "a",
  },
];
export { demoQuiz };
