const quiz = [
  // {
  //   title: "All are living thing except",
  //   a: "Human",
  //   b: "Animal",
  //   c: "Plant",
  //   d: "Chair",
  //   correct: "d",
  // },
  // {
  //   title: "How many teeth does",
  //   a: "30",
  //   b: "31",
  //   c: "32",
  //   d: "33",
  //   correct: "c",
  // },
  // {
  //   title: "How many planets our solar system have?",
  //   a: "10",
  //   b: "9",
  //   c: "8",
  //   d: "7",
  //   correct: "b",
  // },
  // {
  //   title: "What is the name of our galaxy",
  //   a: "Milky Way",
  //   b: "Highway",
  //   c: "Motorway",
  //   d: "Starwars",
  //   correct: "a",
  // },
  // {
  //   title: "Which birds have sharp eyes?",
  //   a: "Sparrow",
  //   b: "Pigeon",
  //   c: "Eagle",
  //   d: "Crow",
  //   correct: "c",
  // },
  // {
  //   title: "How many hours are there in a day?",
  //   a: "24",
  //   b: "22",
  //   c: "23",
  //   d: "26",
  //   correct: "a",
  // },
  // {
  //   title: "What is the formula of Oxygen",
  //   a: "O",
  //   b: "O2",
  //   c: "CO2",
  //   d: "NO2",
  //   correct: "b",
  // },
  // {
  //   title: "How many bones does a human have?",
  //   a: "200",
  //   b: "201",
  //   c: "206",
  //   d: "208",
  //   correct: "c",
  // },
  // {
  //   title: "Who was the first person to land on the moon",
  //   a: "Elon Musk",
  //   b: "Mukesh Ambani",
  //   c: "Bilagtes",
  //   d: "Nelam Stone",
  //   correct: "d",
  // },
  // {
  //   title: "which is the largest content of the world",
  //   a: "Asia",
  //   b: "Europe",
  //   c: "Australlia",
  //   d: "America",
  //   correct: "a",
  // },
  {
    title: "How many teeths an adult human have",
    a: "35",
    b: "32",
    c: "31",
    d: "30",
    correct: "b",
  },
  {
    title: "In which galaxy our solar system exist",
    a: "Milky Way",
    b: "Star Wars",
    c: "Motorway",
    d: "Highway",
    correct: "a",
  },
  {
    title: "Vertical line gradient is",
    a: "Unlimited",
    b: "Unknown",
    c: "Undefined",
    d: "None",
    correct: "c",
  },
  {
    title: "Which is the largest content in the world",
    a: "Asia",
    b: "North America",
    c: "Australlia",
    d: "Europe",
    correct: "a",
  },
  {
    title: "Who won the secound World War",
    a: "Russia",
    b: "United State",
    c: "British",
    d: "Japan",
    correct: "b",
  },
  {
    title: "There are___muslim countries in the world",
    a: "50",
    b: "51",
    c: "52",
    d: "53",
    correct: "a",
  },
  {
    title: "What is the boiling point of water",
    a: "10C",
    b: "20C",
    c: "100C",
    d: "150C",
    correct: "c",
  },
  {
    title: "Which country invented bullet train",
    a: "Japan",
    b: "China",
    c: "America",
    d: "Pakistan",
    correct: "a",
  },
  {
    title: "How many colors does rainbow have?",
    a: "10",
    b: "9",
    c: "8",
    d: "7",
    correct: "d",
  },
  {
    title: "Which bird has no feathers",
    a: "Hen",
    b: "Ostrich",
    c: "Kiwi",
    d: "Peguin",
    correct: "c",
  },
  {
    title: "In__days and hours Earth travel ,It's one year",
    a: "365 Days and 8 hours",
    b: "365 Days and 6 hours",
    c: "365 Days and 10 hours",
    d: "365 Days and 12 hours",
    correct: "b",
  },
  {
    title: "Moon complete his round around the Earth in _ days ",
    a: "22 Days",
    b: "23 Days",
    c: "25 Days",
    d: "28 Days",
    correct: "d",
  },
  {
    title: "Which bird produce largest egg",
    a: "Ostrich",
    b: "Hen",
    c: "Peahen",
    d: "Pigeon",
    correct: "a",
  },
  {
    title: "Currently the owner of twitter is:",
    a: "Elon Musk",
    b: "Bilgates",
    c: "Mukesh Ambani",
    d: "Jeff Becoz",
    correct: "a",
  },
  {
    title: "Which animal live for long time?",
    a: "Lion",
    b: "Toroise",
    c: "Bear",
    d: "Elephant",
    correct: "b",
  },
  {
    title: "Which is the strongest Land animal",
    a: "Tiger",
    b: "Lion",
    c: "Elephant",
    d: "Bear",
    correct: "c",
  },
  {
    title: "Which is the smallest in human body",
    a: "Ear bone",
    b: "Thumb bone",
    c: "Skull",
    d: "Ankale",
    correct: "a",
  },
  {
    title: "Which letter of Alphabet doesn't appear from 1 to 999?",
    a: "D",
    b: "E",
    c: "H",
    d: "A",
    correct: "d",
  },
  {
    title: "Bulb was invented by__",
    a: "Thomas Edison",
    b: "Newton",
    c: "Tesla",
    d: "Tongsatck",
    correct: "a",
  },
  {
    title: "How many secounds are there in a hour",
    a: "3650",
    b: "3600",
    c: "3500",
    d: "3400",
    correct: "b",
  },
  {
    title: "How many years are there in one month",
    a: "1",
    b: "2",
    c: "3",
    d: "none",
    correct: "d",
  },
  {
    title: "Who was the first person that goes in space",
    a: "Nelan Strong",
    b: "Yari Gagarian",
    c: "Elon Musk",
    d: "John Glen",
    correct: "b",
  },
  {
    title: "Which city of Pakistan is known as city of lights",
    a: "Islamabad",
    b: "Lahore",
    c: "Karachi",
    d: "Sukkur",
    correct: "c",
  },
  {
    title: "Which city of Pakistan is known as mini Pakistan?",
    a: "Islamabad",
    b: "Lahore",
    c: "Karachi",
    d: "Sukkur",
    correct: "c",
  },
  {
    title: "Which planet is also called red planet",
    a: "Earth",
    b: "Jupitar",
    c: "Mars",
    d: "Mercury",
    correct: "c",
  },
  {
    title: "Which living thing have 2 hearts",
    a: "Octopus",
    b: "Human",
    c: "Jelly Fish",
    d: "Elephant",
    correct: "a",
  },
  {
    title: "Which is the biggest ocean in the world",
    a: "Paciefic Ocean",
    b: "Indian Ocean",
    c: "Atlantic Ocean",
    d: "Artric Ocean",
    correct: "a",
  },
  {
    title: "Which is the biggest planet in Solar system",
    a: "Earth",
    b: "Jupitar",
    c: "Satrun",
    d: "Uranus",
    correct: "b",
  },
  {
    title: "Which is the hottest planet in Solar system",
    a: "Venus",
    b: "Mercury",
    c: "Neptune",
    d: "Earth",
    correct: "a",
  },
  {
    title: "Who is the father of computer",
    a: "Sundar Pechai",
    b: "Thomas Edison",
    c: "Charles babbage",
    d: "Martin",
    correct: "c",
  },
  {
    title: "In which country Mount Evrest exist",
    a: "Pakistan",
    b: "Nepal",
    c: "India",
    d: "China",
    correct: "b",
  },
  {
    title: "Which is computer brain",
    a: "CPU",
    b: "Motherboard",
    c: "Monitor",
    d: "Mouse",
    correct: "a",
  },
];
export { quiz };
